"""
Django settings for ServiceDesk project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent


def _carregar_env_local():
    # Carrega um arquivo .env local sem depender de bibliotecas extras.
    # Isso deixa o projeto simples de rodar em desenvolvimento.
    caminho_env = BASE_DIR.parent / ".env"
    if not caminho_env.exists():
        return

    for linha in caminho_env.read_text(encoding="utf-8").splitlines():
        linha = linha.strip()
        if not linha or linha.startswith("#") or "=" not in linha:
            continue
        chave, valor = linha.split("=", 1)
        chave = chave.strip()
        if chave and chave not in os.environ:
            os.environ[chave] = valor.strip().strip('"').strip("'")


_carregar_env_local()


def _env_bool(name, default=False):
    # Converte flags de ambiente em booleano com valores comuns do shell.
    valor = os.getenv(name)
    if valor is None:
        return default
    return valor.strip().lower() in {"1", "true", "yes", "on"}


def _env_list(name, default=None):
    # Aceita listas separadas por vírgula, como ALLOWED_HOSTS.
    valor = os.getenv(name, "")
    if not valor:
        return default if default is not None else []
    return [item.strip() for item in valor.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-3^ix-hwx$zf^q1bbe#)%b)32lth#%jsy)0v+z_h)r7f!yp(%io",
)
DEBUG = _env_bool("DJANGO_DEBUG", True)
ALLOWED_HOSTS = _env_list("DJANGO_ALLOWED_HOSTS")


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "chamados",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ConfigDjango.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ConfigDjango.wsgi.application"


# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
LANGUAGE_CODE = "pt-br"
TIME_ZONE = "America/Sao_Paulo"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"

# Configuracao do servidor TCP de notificacao em tempo real.
SOCKET_NOTIFICACAO_HOST = "127.0.0.1"
SOCKET_NOTIFICACAO_PORT = 8765

AUTHENTICATION_BACKENDS = [
    "chamados.backends.EmailOuUsuarioBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

GOOGLE_OAUTH_CLIENT_ID = os.getenv(
    "GOOGLE_OAUTH_CLIENT_ID",
    "1053202065034-3h5p2gtlajn3o0k1i8ir66tbo8i7fs3k.apps.googleusercontent.com",
).strip()
GOOGLE_OAUTH_CLIENT_SECRET = os.getenv(
    "GOOGLE_OAUTH_CLIENT_SECRET",
    "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",
).strip()
GOOGLE_OAUTH_ENABLED = bool(GOOGLE_OAUTH_CLIENT_ID and GOOGLE_OAUTH_CLIENT_SECRET)
FRONTEND_GOOGLE_CALLBACK_URL = os.getenv(
    "FRONTEND_GOOGLE_CALLBACK_URL",
    "http://localhost:5500/pages/auth/google-callback/index.html",
).strip()

# Configuração do provider do Google:
# - escopo de perfil e e-mail
# - e-mail como verificado
# - login/autocadastro sem tela intermediária
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "VERIFIED_EMAIL": True,
        "EMAIL_AUTHENTICATION": True,
    }
}

# O fluxo social fica mais leve em desenvolvimento:
# entra direto pela conta Google e associa por e-mail quando fizer sentido.
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_LOGIN_ON_GET = True

if GOOGLE_OAUTH_ENABLED:
    SOCIALACCOUNT_PROVIDERS["google"]["APP"] = {
        "client_id": GOOGLE_OAUTH_CLIENT_ID,
        "secret": GOOGLE_OAUTH_CLIENT_SECRET,
        "key": "",
    }

# URL de autenticacao usada pelo decorator @login_required (RF02).
LOGIN_URL = "/login/"

# Apos autenticar via Google, o backend entrega JWTs para o frontend estatico.
LOGIN_REDIRECT_URL = "/api/v1/auth/google/success/"

# Apos logout, retorna para a tela de login.
LOGOUT_REDIRECT_URL = "/login/"


# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
